apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-restic-pv
spec:
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/Apps/restic
    server: 192.168.88.6
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-restic-pvc
  namespace: restic
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
  volumeName: nfs-restic-pv
  storageClassName: ""