---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: prowlarr-postgres
  namespace: media
spec:
  encryptedData:
    password: AgB7CjIYFY9KbPWDiMBU7XY9N4uJ9Mqn8OvPdUAVk3oS+ccrhXHMqfznoO4BmdGUlqEnQOvP2dOtv+f8yBlNdhmCDTR0DucQ/tWkkMUs675zUv+uscd1roGGeoyelPYY6GJNCMcJ6HzAlPo6w+04A9CpOmZYwdSnShJLD4vJghMYt0fES3PtUmAelOT+VfpHaVP3w3DYh0BfIb99BDNteiea6TCJKVmPyQbqARz9BOh/++91/0m+2vwWv5fPLCjRYZhDrznH4LcYqadPxJKS9SDymfTDufMNBRMEr5ov5Kt2m7wZOSbYEv4aOwLjdwQyzHZMJawaiIqsJDEHT0HIgjDrG3ZGpXgLqWpwep7XASuexo9Ds2MJIIRqLc8xwdVfHQ3bkXysTdO1RJl3j2Q3AT/wozmevhiZu0Xcf+KDhDuVe1DJjskbx65NjUQe1suwnarNRlpDLK3DwJ6lVP1/fts4m7KJcBExYRWXpmu4uCVTxXodCaXV9T+Sxr8gicTg3er/CR4qxmNpvkh0RhoPmasnZPvfMcMl6aCjT1SrP466gUkEyp2nVbmGdQkhWQbsJeossPSFd0GLQkC7yZ0WN2cDjRNinprcR+VZR2J0pk3eO/pqhL4tTZU3cgSVJ13EkYHiH3G1F4RlswMndr7cyIBOl4JH4eSiJJYloqGNqTaa/jAmLa0/mYaCXxkWsUe2M7ex0n3SSWHYL59jJ8fjelJbTu5b2g==
    username: AgCqCXhh5lk9SvT+6o+tIN8VMFCHULF0wYL+aP+Skr6yg9dnAv1vCP/H93w9s+vJXGplej5RLvgoE63wOrjwxhI1FqzPsg8vZHgL0YmDEqFBeCTJzDbTbUt9eRSTQ1bV6iZUa/ckTB1xfoo7/l9+UNS0vbhSC2JwD2PQFwcIXc6BtsHx7U1Q06BmwI6TUhr4KRldVpjhRZ2aBxeO2aHhgbxosSnXFY9Xw0ZiWHgptn3IduvElVBsIDBLcab0zHN4tF1oX7VVdYPq/4Vwu/o3E+SAUQo/OPndh84r3XkgVuRg8u50Jih2xL6kJEu8JEEJTKPQu8mv/95fp26EuEbYLJQqN9taum1DjlGXXiyi8BWtE20g6a28Lt8D0jLyF/wBarN4O9NH3myCwnXTX7spgKjunZQkDN4PSig1PUHFFmJiyQbFmImVPcsAqbhgR/AhLVBJJdSIJUUy1Ck6ssL+rY2gbmo68gHqkTst6OfauqlQIIxJ7593I/dhXTPRR/l5UNlFSncY5x6nS/LNgmfb5TMUY57RTJ9nl+kTQOZhsWVUIXxVkk2l15YJVM32H/DK3xuaLO2e8G15yzrhNpo3X1CCXZsLEKP3P1QSUnvH32e+0YFYeO3QOUCQWLFG1Iq06goJwT+Mnx619pWkdu4hFOcTSkcpE+DhM5pJFCkBahhpFdv2XoDOF659lkqeT5nrWaCsBZVR3HP8mw==
  template:
    metadata:
      name: prowlarr-postgres
      namespace: media
    type: kubernetes.io/basic-auth