apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bakito.net
    targetRevision: 3.3.1
    chart: sealed-secrets-web
    helm:
      values: |
        sealedSecrets:
          namespace: sealed-secrets
          serviceName: sealed-secrets-controller
        service:
          type: NodePort
          nodePort: 30004
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true