---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: yeungjin01-minecraft-backup
  namespace: game
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  # The PVC to be backed up
  sourcePVC: yeungjin01-minecraft-pvc
  trigger:
    # Take a backup every 30 minutes
    schedule: "0 0 12 1/1 *"
  restic:
    # Prune the repository (repack to free space) every 2 weeks
    pruneIntervalDays: 30
    # Name of the Secret with the connection information
    repository: yeungjin01-minecraft-restic-config
    # Retention policy for backups
    retain:
      hourly: 6
      daily: 5
      weekly: 4
      monthly: 2
      yearly: 1
    # Clone the source volume prior to taking a backup to ensure a
    # point-in-time image.
    copyMethod: Clone
    # The StorageClass to use when creating the PiT copy (same as source PVC if omitted)
    #storageClassName: my-sc-name
    # The VSC to use if the copy method is Snapshot (default if omitted)
    #volumeSnapshotClassName: my-vsc-name