apiVersion: apps/v1
kind: Deployment
metadata:
  name: yeungjin01
  namespace: game
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: yeungjin01-minecraft
  template:
    metadata:
      labels:
        app: yeungjin01-minecraft
    spec:
      containers:
      - name: minecraft-server
        image: itzg/minecraft-server  # 가장 널리 쓰이는 마인크래프트 서버 이미지
        ports:
        - containerPort: 25565
        env:
        - name: EULA
          value: "TRUE"
        - name: VERSION
          value: "26.1.2"
        - name: TYPE
          value: "PAPER"
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "8Gi"
        volumeMounts:
        - name: minecraft-data
          mountPath: /data
      volumes:
      - name: minecraft-data
        persistentVolumeClaim:
          claimName: yeungjin01-minecraft-pvc