apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yeungjin01-minecraft-pvc
  namespace: game
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi