image:
  repository: itzg/minecraft-server
  tag: latest
  pullPolicy: Always
  pullSecret: ""
replicaCount: 1
nameOverride: ""
fullnameOverride: ""
resources:
  requests:
    memory: 4Gi
    cpu: 1
lifecycle:
  postStart: []
  preStop: []
workloadAsStatefulSet: false
strategyType: Recreate
nodeSelector: {}
tolerations: []
affinity: {}
revisionHistoryLimit: 10
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 3000
  runAsNonRoot: true
  fsGroup: 2000
  seccompProfile:
    type: RuntimeDefault
securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
livenessProbe:
  command:
    - mc-health
  initialDelaySeconds: 30
  periodSeconds: 5
  failureThreshold: 20
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  command:
    - mc-health
  initialDelaySeconds: 30
  periodSeconds: 5
  failureThreshold: 20
  successThreshold: 1
  timeoutSeconds: 1
startupProbe:
  command:
    - mc-health
  enabled: false
  failureThreshold: 30
  periodSeconds: 10
initContainers: []
sidecarContainers: []
extraVolumes: []
extraDeploy: []
extraPodSpec: {}
minecraftServer:
  eula: "TRUE"
  version: "26.1.2"
  type: PAPER
  forgeVersion: null
  forgeInstallerUrl: null
  spongeVersion: null
  bukkitDownloadUrl: null
  spigotDownloadUrl: null
  paperDownloadUrl: null
  ftbModpackId: null
  ftbModpackVersionId: null
  cfServerMod: null
  fabricLauncherVersion: null
  fabricLoaderVersion: null
  ftbLegacyJavaFixer: default
  difficulty: easy
  whitelist: null
  ops: null
  icon: null
  maxPlayers: default
  maxWorldSize: default
  allowNether: default
  announcePlayerAchievements: default
  enableCommandBlock: default
  forcegameMode: default
  generateStructures: default
  hardcore: default
  maxBuildHeight: default
  maxTickTime: default
  spawnAnimals: default
  spawnMonsters: default
  spawnNPCs: default
  spawnProtection: default
  viewDistance: default
  levelSeed: null
  gameMode: survival
  motd: Welcome to Minecraft on Kubernetes!
  pvp: default
  levelType: DEFAULT
  generatorSettings: null
  worldSaveName: world
  downloadWorldUrl: null
  forceReDownload: false
  downloadModpackUrl: null
  removeOldMods: false
  vanillaTweaksShareCodes: []
  resourcePackUrl: null
  resourcePackSha: null
  resourcePackEnforce: false
  onlineMode: default
  enforceSecureProfile: default
  memory: 4096M
  jvmOpts: ""
  jvmXXOpts: ""
  overrideServerProperties: default
  serviceAnnotations: {}
  serviceType: ClusterIP
  nodePort: null
  servicePort: 25565
  clusterIP: null
  loadBalancerClass: null
  loadBalancerIP: null
  externalIPs: null
  ipFamilies: null
  ipFamilyPolicy: null
  modUrls: []
  pluginUrls: []
  spigetResources: []
  extraServiceSpec: {}
  modrinth:
    projects: ["swbUV1cr"]
    downloadDependencies: none
    allowedVersionType: default
  autoCurseForge:
    apiKey:
      key: CHANGEME!
      existingSecret: ""
      secretKey: cf-api-key
    pageUrl: ""
    slug: ""
    fileId: ""
    filenameMatcher: ""
    excludeMods: []
    includeMods: []
    excludeIncludeFile: null
    forceSynchronize: false
    setLevelFrom: ""
    parallelDownloads: 4
    overridesSkipExisting: false
  rcon:
    enabled: true
    withGeneratedPassword: false
    port: 25575
    password: 8yMTEKMX2BheglJIBMVdyrR4hyyAjaaH
    existingSecret: null
    secretKey: rcon-password
    serviceType: ClusterIP
    nodePort: null
    clusterIP: null
    loadBalancerClass: null
    loadBalancerIP: null
  tty: true
  extraPorts: []
  query:
    enabled: false
    port: 25565
extraEnv: {}
envFrom: []
persistence:
  labels: {}
  annotations: {}
  storageClassName: longhorn
  dataDir:
    enabled: true
    Size: 5Gi
    accessModes:
      - ReadWriteOnce
podAnnotations: {}
podLabels: {}
deploymentAnnotations: {}
deploymentLabels: {}
serviceAnnotations: {}
serviceLabels: {}
rconServiceAnnotations: {}
rconServiceLabels: {}
mcbackup:
  enabled: false
  image:
    repository: itzg/mc-backup
    tag: latest
    pullPolicy: IfNotPresent
  initialDelay: 2m
  backupName: null
  backupInterval: 24h
  pauseIfNoPlayers: "false"
  pruneBackupsDays: 7
  rconRetries: 5
  rconRetryInterval: 10s
  excludes: "*.jar,cache,logs"
  backupMethod: tar
  destDir: /backups
  linkLatest: "false"
  compressMethod: gzip
  zstdParameters: -3 --long=25 --single-thread
  rcloneRemote: null
  rcloneDestDir: null
  rcloneCompressMethod: gzip
  rcloneConfig: null
  resticRepository: ""
  resticAdditionalTags: mc_backups
  pruneResticRetention: --keep-daily 7 --keep-weekly 5 --keep-monthly 12 --keep-yearly 75
  resticHostname: null
  resticEnvs: {}
  extraEnv: {}
  envFrom: []
  resources:
    requests:
      memory: 4Gi
      cpu: 1
  persistence:
    annotations:
      - storageClassName: longhorn
    backupDir:
      enabled: false
      Size: 1Gi
      accessModes:
        - ReadWriteOnce
