apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-restic-config
  namespace: auth
type: Opaque
stringData:
  RESTIC_PASSWORD: "vaultwarden-restic-config"
  RESTIC_REPOSITORY: "rest:http://rest-server.restic.svc.cluster.local/auth/vaultwarden"