apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: auth-postgres-vaultwarden
  namespace: auth
spec:
  cluster:
    name: auth-postgres
  name: vaultwarden
  owner: vaultwarden
  databaseReclaimPolicy: retain