apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-config
  namespace: auth
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi