apiVersion: v1
kind: ConfigMap
metadata:
  name: proxmox-ca
  namespace: external
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFzTCCA7WgAwIBAgIUKWqWsVQH9WBTknnXQ4f53ieAxWcwDQYJKoZIhvcNAQEL
    BQAwdjEkMCIGA1UEAwwbUHJveG1veCBWaXJ0dWFsIEVudmlyb25tZW50MS0wKwYD
    VQQLDCQ2N2M5MzJlOS03Nzg0LTRkNmQtYjU4MC0yOGQ0MWIwZTU4NjExHzAdBgNV
    BAoMFlBWRSBDbHVzdGVyIE1hbmFnZXIgQ0EwHhcNMjUwOTA5MTYwMjQ4WhcNMzUw
    OTA3MTYwMjQ4WjB2MSQwIgYDVQQDDBtQcm94bW94IFZpcnR1YWwgRW52aXJvbm1l
    bnQxLTArBgNVBAsMJDY3YzkzMmU5LTc3ODQtNGQ2ZC1iNTgwLTI4ZDQxYjBlNTg2
    MTEfMB0GA1UECgwWUFZFIENsdXN0ZXIgTWFuYWdlciBDQTCCAiIwDQYJKoZIhvcN
    AQEBBQADggIPADCCAgoCggIBANWs2PgYxTWLHp/e/xAXD61/+ZddQtHgBh2Z9yB4
    PKZqNUyO5ycuErCi2Bd+EOh2l3EZhI+Z1t3dSvDnZf5RgkdwgKrfr49eRfUTQz8c
    vSskEUsvJYPjwAZsKLQIKGPkff8M5T8DnNNOSE7Ig3ICzq8wLQWHcQTZWiRlY9u4
    fr+iMOcN8PcmMZsPqRtBdnazad7EhjNFwg9/l6gfdQQw6wZtSQQo3uAN2yyAPFv3
    gWJx5FKv6AOY3HM2hA5gb4DaLIkQbPof5x1SzIb/nvG+ZBqcff5BkQmNydwYZUju
    4BoKGmaCtBXc6GfqFxsWtOaO/kuQoMkVGoBrpz2q4D0NQZ0OYUbomat9GPZz16G4
    qNQNvhFeN5FnxLDvaej5tNzjCBGWYqZcpekhQMf0EhhfqlNqIc34c5crey7277Uv
    VS7bMhF8/kuQuYtkJugZMERxNkqxZUfEXjQTxz5O91P9QpH2L8JvtLkF38Huq03K
    Aoxs3Ks46MhY3ogUm4V4l+zrBOIoA2rYOBCHwgwgFmP3LZEhJTmwp+nCI7cS1WM8
    oYeLAHqF/cslQPiGQ/cY7h8r3CuGMW3zhpV5x3a8mDM05EuUA8iIiVRz9mEs5D+i
    doxf8CXZYKkWof7CoZMInkmCDe8covdMaCvXCGcbcxledjHpCYDXIZf3Q+sHKBc2
    IfDBAgMBAAGjUzBRMB0GA1UdDgQWBBQCWhQzWngLIhGsleyhcecmXHC/6jAfBgNV
    HSMEGDAWgBQCWhQzWngLIhGsleyhcecmXHC/6jAPBgNVHRMBAf8EBTADAQH/MA0G
    CSqGSIb3DQEBCwUAA4ICAQA/Byrcg0f/0Ot7i8gzZfHzYoVx4tkeSlq9OwapYuG/
    PA3cjTWu69hx+IFaDulvmHJfzITcCVlEwj1Q9beOeZROQW2tV5aGgeDqz3NcGXuK
    rLsRJrN1sI0DgZqQkugsQa2egpEr38wfLh0ephxQatBq7u7HJe6G7QuyuCZmeK30
    fjmSwmY4LB8SbDDMubu6xisUAT23WEEAezftqWLPfBTh/lcCPcrTd7EOSANIqPPM
    DV+Xr8yPj58ie9zzq/Fgh3KVQCIMywbyUP86+BbpgKmLJjXEV79U089dzQ5OeRK7
    vhrHQZxUtmremqOHZ45atgq8YVbv5FH6rM//y7K1GOQaQ/lc4Yil4uZKcH6Os49B
    KQxAr/kOh9IaxoNZsG7TWfRREmwslBD7nEQOwyrfySEKo2erK3vtK/j7fkuZBldJ
    qEzSvoMVjM/V0/o2Jzm/hUk6VqGlbowV2qOuW6AQ4deD4r6WQi/q1EN2BlT89zbp
    +PzjlDiwNBBTkvIE+HoPmI0Ld05RRcnj81dwP9GoxY6cPZ2jXhjDHiy/Vcc02d55
    aZNWmZgKtnrDyYuc6pOqD/f0a+msuSyrg/o/3RJISic2gwV3tyKls/C1bOO6Qc6t
    9lt3GlvsiwVIrOnZ5MqfHzEWUpQAFErOuqElyesn23leIVYiIGZnpu81ozDpCkd/
    Kw==
    -----END CERTIFICATE-----
