apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: proxmox-internal-route
  namespace: external
spec:
  parentRefs:
  - group: gateway.networking.k8s.io	
    kind: Gateway	
    name: gateway-internal
    namespace: default
  hostnames: ["pve.internal.lazydogs.work"]
  rules:
  - backendRefs:
      - group: ''	
        kind: Service
        name: proxmox-svc
        port: 8006
        weight: 1
    matches:
      - path:
          type: PathPrefix
          value: /
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: proxmox-skip-tls-backend-policy
  namespace: external
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: proxmox-svc
      sectionName: https
  validation:
    hostname: pve01.home.lab
    caCertificateRefs:
      - group: ""
        kind: Secret
        name: proxmox-ca