replicaCount: 1
image:
  repository: itzg/mc-router
  tag: latest
  pullPolicy: Always
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""
deploymentStrategy:
  type: Recreate
deploymentAnnotations: {}
deploymentLabels: {}
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
services:
  api: {}
  minecraft:
    type: loadBalancer
    port: 25565
    loadBalancerIP: 192.168.88.152
  extraServiceSpec: {}
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
extraVolumes: []
extraEnv: {}
extraPodSpec: {}
extraDeploy: []
minecraftRouter:
  autoScale:
    up:
      enabled: false
    down:
      enabled: false
      after: ""
    configObject: Secret
    allowDeny: {}
  connectionRateLimit: 1
  cpuProfilePath: ""
  debug:
    enabled: false
  defaultServer: {}
  mappings:
    - externalHostname: yeungjin01.lazydogs.work
      host: yeungjin01
      port: 25565
  metrics:
    backend: discard
  ngrokToken: {}
  simplifySrv: false
  useProxyProtocol: false
  showVersion: false