
ipam:
  mode: kubernetes

kubeProxyReplacement: true
gatewayAPI:
  enabled: true
l2announcements:
  enabled: true
externalIPs:
  enabled: true

k8sServiceHost: "localhost"
k8sServicePort: 7445


securityContext:
  capabilities:
    ciliumAgent:
      - "CHOWN"
      - "KILL"
      - "NET_ADMIN"
      - "NET_RAW"
      - "IPC_LOCK"
      - "SYS_ADMIN"
      - "SYS_RESOURCE"
      - "DAC_OVERRIDE"
      - "FOWNER"
      - "SETGID"
      - "SETUID"

    cleanCiliumState:
      - "NET_ADMIN"
      - "SYS_ADMIN"
      - "SYS_RESOURCE"

cgroup:
  autoMount:
    enabled:
  hostRoot: "/sys/fs/cgroup"

operator:
  replicas:
  prometheus:
      enabled: true

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true
    service:
      type: NodePort
      nodePort: 30000
  metrics:
      enableOpenMetrics: true
      enabled:
          - "dns"
          - "drop"
          - "tcp"
          - "flow"
          - "port-distribution"
          - "icmp"
          - "httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload"
