apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: gateway-internal
  namespace: default
spec:
  gatewayClassName: cilium
  addresses:
    - type: IPAddress
      value: 192.168.88.150
  listeners:
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - name: lazydogs-work-key-pair
        kind: Secret
    allowedRoutes:
      kinds:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
  - name: http
    hostname: "*.internal.lazydogs.work"
    port: 80
    protocol: HTTP
    allowedRoutes:
      - group: gateway.networking.k8s.io
        kind: HTTPRoute
    routes:
      filters:
      - type: RequestRedirect
        requestRedirect:
          scheme: https
          statusCode: 301
