apiVersion: v1
kind: Service
metadata:
  name: kubeseal-webgui
  namespace: kube-system
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.88.153
  externalTrafficPolicy: Local
  ports:
  - port: 80 
    targetPort: 80
    nodePort: 31080
    name: http
  selector:
    app.kubernetes.io/name: kubeseal-webgui
