apiVersion: v1
kind: Service
metadata:
  name: kubeseal-webgui
  namespace: kube-system
  labels:
    run: kubeseal-webgui
spec:
  type: LoadBalaner
  loadBalancerIP: 192.168.88.152
  externalTrafficPolicy: Local
  ports:
  - port: 80 
    targetPort: 80
    nodePort: 33000 
  selector:
    app: kubeseal-webgui
