global:
  domain: "argocd.internal.lazydog.work"

configs:
  params:
    server.insecure: true

server:
  service:
    type: nodePort
    nodePort: 30001

controller:
  replicas: 1

repoServer:
  replicas: 1

applicationSet:
  replicas: 1