apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.11.2
      helm:
        valueFiles:
          - $repo/argocd/infrastructure/longhorn/longhorn-values.yaml
    - repoURL: https://github.com/sonhs99/kube-bootstrap.git
      targetRevision: main
      ref: repo
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true