apiVersion: v1
kind: ConfigMap
metadata:
  name: longhorn-default-resource
  namespace: longhorn-system
data:
  default-resource.yaml: |
    "backup-target": "nfs://192.168.88.6:/Apps"
    "backup-target-credential-secret": ""
    "backupstore-poll-interval": "180"