apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rcon-web-admin
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://itzg.github.io/minecraft-server-charts/
      chart: rcon-web-admin
      targetRevision: 1.2.1
      helm:
        values: |
          rconWeb:
            username: admin
            password: "rcon-admin"
            rconHost: yeungjin01-minecraft-rcon
            rconPasswordExistingSecret: "yeungjin01-minecraft-rcon"
            rconPasswordKey: "rcon-password"
            websocketRcon: false
            websocketUrl: "ws://rcon.internal.lazydogs.work:4327/ws"
            websocketUrlSsl: "wss://rcon.internal.lazydogs.work:4327/ws"
  destination:
    server: https://kubernetes.default.svc
    namespace: game
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true