---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: pastey-backup
  namespace: tools
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  sourcePVC: pastey-config
  trigger:
    schedule: "0 0 0/6 1/1 *"
  restic:
    pruneIntervalDays: 30
    repository: pastey-restic-config
    retain:
      hourly: 6
      daily: 5
      weekly: 4
      monthly: 2
      yearly: 1
    copyMethod: Clone
    #storageClassName: my-sc-name
    #volumeSnapshotClassName: my-vsc-name