apiVersion: v1
kind: Secret
metadata:
  name: pastey-restic-config
  namespace: tools
type: Opaque
stringData:
  RESTIC_PASSWORD: "pastey-restic-config"
  RESTIC_REPOSITORY: "rest:http://rest-server.restic.svc.cluster.local/tools/pastey"