apiVersion: apps/v1
kind: Deployment
metadata:
  name: pastey
  namespace: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pastey
  template:
    metadata:
      labels:
        app: pastey
    spec:
      containers:
      - name: pastey
        image: bellamy/wallos:latest
        env:
        - name: PASTEY_LISTEN_PORT
          value: "5000"
        - name: PASTEY_DEFAULT_THEME
          value: Dark
        - name: PASTEY_BEHIND_PROXY
          value: "true"
        - name: PASTEY_FORCE_SHOW_RECENT
          value: "true"
        - name: PASTEY_RESTRICT_PASTING
          value: "true"
        - name: PASTEY_WHITELIST_CIDR
          value: 127.0.0.1/32,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
        - name: PASTEY_RECENT_PASTES
          value: "20"
        volumeMounts:
        - name: config
          mountPath: /app/data
        ports:
        - containerPort: 5000
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: pastey-config