global:
  env:
    - name: AUTHENTIK_POSTGRESQL__HOST
      value: auth-postgres-rw

    - name: AUTHENTIK_POSTGRESQL__PORT
      value: "5432"

    - name: AUTHENTIK_POSTGRESQL__NAME
      value: authentik

    - name: AUTHENTIK_POSTGRESQL__USER
      valueFrom:
        secretKeyRef:
          name: authentik-postgres
          key: username

    - name: AUTHENTIK_POSTGRESQL__PASSWORD
      valueFrom:
        secretKeyRef:
          name: authentik-postgres
          key: password

    - name: AUTHENTIK_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: authentik-auth-secret
          key: token
  envFrom: []

authentik:
    error_reporting:
        enabled: true

postgresql:
    enabled: false