---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-auth-secret
  namespace: auth
spec:
  encryptedData:
    token: AgAkdrXOPMoWr7YMnO4ZY27ypbGNSWFe15jekkuhSIOGgYChtmpy0Yk6zsyvOgOkQE4eEERlpMTpazFmr/IrN+SQE08FGRlwG5IR28cLXZkB1iayx+LopCn3+WPIT06tB3B8lVDHQhfsMg18PRIwUFf7B1lneAWYvP8a2ti7/eVXhRlgFFijngGYX8yW7BZa+Lsu5J8CkbmdIeS9Y6pVTbggdIVo0STQP+suGPlQG6ruqPFAwL0UqwhKh/ZKTcTy9Bb6HJRajgKCIj4Nhpmji07VLH7q47M4B/zZvAZWHItfam20slsOUZi1e+f+sm7sldiX3S9FkrSqwYXfqOzmY9xQFA7vmJPyRon80ej2pT7Z7e2vXb7LT4jxHpjzNehvanUMwJWTKPJQRSbVwxTerkpxEpiGOBVwGiJWUhtqXq/1ni74KY57NBjnceNpoIIh0rjzZ0PrMC6bvbPZiFYsgiaW7/MRyS97wmwM+GMdXxEMIrYTvEOPPJA0JNoPsv966Tx2epvhNn3kYCGEeL6n0LJ4/37699O4kju4IGO0XIoPIhmkhiWJ5n3eUm3yP3l/j+u/cORnOYE4aWKntrfzB/MxSVjuBApehnLLUhYykOwBe/4jC3F9nVS+xQtGkz/4vIf2uCfIdP1w5Go4VxDhDSdkgENA3Gk/O6iQcIzEUjjQ3W2y0KDcPt1ciPVnA/RqKRPIgUxJMr9K+cdha7Fhis/HEkrom7IRsBMdMTb+jCYyyMUq1TNrGi23CTr69qzFLKW8eSHFZpyYBRBkwTI=
  template:
    metadata:
      name: authentik-auth-secret
      namespace: auth
    type: Opaque