apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: auth-postgres-authentik
  namespace: media
spec:
  cluster:
    name: auth-postgres
  name: lidarr
  login: true
  superuser: false
  createdb: false
  createrole: false
  replication: false
  connectionLimit: 30
  databaseRoleReclaimPolicy: retain
  passwordSecret:
    name: authentik-postgres