---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgres
  namespace: auth
spec:
  encryptedData:
    password: AgCs5f6HxS1VW3SdVHPFft51iN+mmlGMFURNbCKkXQbhJDuz2sgpF9xQXHkXdow9AEaqFNc/ape10Cn7dT2fqcduK9T4wmTKDNVyPP2SZQYbARY2AAYLCMrfDdXOQBogcwE9tzwy0KVclJ0lDSyICVIs+Dklsyg5r6wyHtnBQyzPlLfCKvO4BXYFvKk7CqzwvuxhEoxjqRc5L2WnofNDzgn4U9NF1pAySzcgKlCD3A4Ax8qFJDEtKZu7Ixly4sg1E68UQ/NEnxT/g+Uof83MFSZf1YYGS9fiFsw/DQQTYqAvCZBq84+wUOd+6183fGvU+gmv+T2TdSVcygDFFwyVfo0odsjhJF9KUUoAS98BgYqgXitpjXCTaIMypuOvy/x49C6iwQICfrInlaftrWAvfWJJlvJBrQwNZ+0J1KNNj3V8pguFF4sEF1BFAzyZ54Qyz5cO4iHkEKWxtVmHVQLcLDxP8EJcCtyOo9R743P+sVME3CVUVecgXZv+E3dOeWxjWkXjAHCcJPxnTlU/Diomb26zjN54RPMy/zsgUjRmPWr0dFosiE49Nroaz1Lb5uZi+P47WBDWzmUFryDFOiSel1uiVYv2gg3jQPf7okLDhuW5ofNdML8C+MpLQj765mo7OPoMIYfl0znKOyGQGONiEIhVh9xogtMgqTpiqY7P4vVfGp4jKx8eYutVQ6t8iajsGCem5Xis5W3PH9Jip7oAyqJAAjw8yw==
    username: AgATfrmglxBbPBWGyRFf/HuzspVv2ugCugUEtBrWR5aHO0p+9MuyxMcrYF/xm4H2MCVKEICxZKq9Sp9h2i51GRJR03kqk9Fo5h5w0b1NWtAnN6FEb4H//MbFUg35wIz0A7TRzDDXW5Zh2Ty1NdYQiwCCRaZ4oI2Af9OXfSjjVEmxmJU3zYvXu0yHLvqQTvF3h9gvy/fOY3RFt2GgVjJW85m9207O7J63wY8R1ZlAQiA7V5uyY+GoSDHt3+IYxe79vLQfYRUr1FcPl9SMyyukQjRB4xP1I6D98ni9y/dZZSQY6qbda0l5EXv7Rk9uIHumHXB/YX1E71TW9m71R/Io5hM4FyAz0gZZ5SihEZo1fRKgz2SNZD1PMM/pzwWiYLB5IZvUZyIOAQuWIAuacXaXOjyCTK7eM8aRYduS2tPBH0En1PtDf3/iL7zmmvKh0WcQjqB0453FYX41IYqx8KOIePtcla8Gi/+O2UZD/RH4ruqglUGr9dg6mCFNEuIp5+iFb93LIwn7x4ULFJbBmT4ObQRILXSubQy+U87d50ZpFT8AOcb9Ur3gHxcw/yURSoj/NRtcTfnM26GzdnNoHTaB+EL+6P9v5yQNCrIU9XFmCteqIUgxeqsl/DuABE/Ev4Gsm7Ra7ApUwd6Rgz1LC9AKX3XpKuAOUpif9pu8Q4X86v0ZkqeyO+rWcxvslG9Il1Kz2IsJegr04+f1vYo=
  template:
    metadata:
      name: authentik-postgres
      namespace: auth
    type: kubernetes.io/basic-auth