apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: auth-postgres-auth
  namespace: auth
spec:
  cluster:
    name: arr-postgres
  name: authentik
  owner: authentik
  databaseReclaimPolicy: retain