apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-server
  namespace: restic
  annotations:
    argocd.argoproj.io/sync-wave: "-35"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-server
  template:
    metadata:
      labels:
        app: rest-server
    spec:
      containers:
      - name: rest-server
        image: restic/rest-server:latest
        env:
        - name: OPTIONS
          value: "--path=/data --no-auth"
        volumeMounts:
        - name: backup-storage
          mountPath: /data
        ports:
        - containerPort: 8000
      volumes:
      - name: backup-storage
        persistentVolumeClaim:
          claimName: nfs-restic-pvc