apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-rest-pv
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
spec:
  capacity:
    storage: 400Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/Apps/restic
    server: 192.168.88.6
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-rest-pvc
  namespace: restic
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 400Gi
  volumeName: nfs-rest-pv
  storageClassName: ""