---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: radarr-postgres
  namespace: media
spec:
  encryptedData:
    password: AgCQNaBy8Lqeiz395g+xFthpamsQdWFfRaOhYRw13V34rIWA6G8NSJWIo0Jmt48hlnagl/GtTch+/ODMB8XQl7Lo/WwQFv1QbtrFI3ih8MZbrOiK9ilf5N79t+tqp1gDjJTQ9LOUrRIFTAv3IO41z0XD9MwIYpfatUB2LhK7pF392x3oEDDOczZIYcL4R6m+huhK0Un/VlWERlv1ZPym6xaLdLVRlU6hOZmfm1sj2fuUlps3NIT0Yy7oiVRv8tLeiiHkk1EmGD9KuYSWH8pPvbygZBXn3p0AQ4opGxTw7GQjjn8LslkAI90gBaGund9s8S3C2PxlSJj42f5aMk5x33OE9cFDkU1+UbBLqj0PdE3AoFr0clQW1ee2laW8X+xyqSOMiw0temdea4FNxU/K6vEVmbp6+Jwn9P42H7cgtO0Bjr2utOVjmC+B0ajkRhti8kNrZFMVI2eRnvJ/Zf7ugb/yH8BkkS5stqfKMOjv2Gcunw++XyDdOy4JBOAzGWZAK3SWD8oNi8ZR+qdNy9ViKWdHO0f0ysJQI6cmwRtL2EnTV5vzqMKNFV/Cv+pDSQfa5fxV8pzXbfewnoIWauprE/IZbUxcsNodljVg5vNHftDPZ+mWhBRhB+KYM0UkyaI8XhVWnXeaMt6iV5kiPXYCwgNTeO/GaK1HWvmKf7ZpFbarZ9J5yq8Lt16wsz/Ck/Gn227aUEYd8Vr46/aqueuPszXSMUFf0w==
    username: AgBlSb9v6Lj+uvyyjmBF14C8llWdT/xEki0cPz1G/FCtQ8YhYAXTkAA4CPa0ejRQwvbpA/IEvSi51COwoZqBwfvExAf6dPWKPEoVtaJJCTBI2gQ8Fp7u5jrPm12NK3nNJXk6xSYm1niLETIsPZWr+aMJh5+BqogeyYlCv6ugXcAaJNrKNpYSCTA5pAxrZE6a2Xd+SBBFFeX2NeH1p6ChVpu8+bFZ/sSP06Sgq9grGw6iYwOeCk3B6gQ4e7IE1nsBEPIGVdiXEPd0peyHpUpY9P7Mr2V3UPxEK+7ECGbYzGELx0vTPEOzJeQmOfrD03k9Ow5oOTUFUGnlBQv8lsfH1WM8swd1+LUhrXYqkUsoiA1if1fC0shIbeZPy4cdoYiflI7jNxQcdlhcGm8i86h4vFRJC0KB1VfMbLlapQqtbIk14pXs3w/d6Fmy0k1fDPK0+D27lJW08TQoxdcOoN6x1zK/rylcCtkhvIN89L+IRRjy85vhApI2bOJuXn+fXiqbaov9WpBjzXdzE/daQ3FbHHF3MCxo5n7sU470Dy0vz7cJFXYRUOdm9uy9Rk9KFS9MF+2FTfEKmVEaaLXZaQJk9fsoD+aPdpAVwroBnL1uSTkfES9VnnbuPhJeYz/omlWMvW1sez4OGPUQqnsJtl9VhaNGBhZ+ZQfqpAFzIgmzepSsC8RmaQ6ay+VrcqHdWy+dkrrYqJ2ZE+Y=
  template:
    metadata:
      name: radarr-postgres
      namespace: media
    type: kubernetes.io/basic-auth