apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: lscr.io/linuxserver/radarr
        env:
        - name: PUID
          valueFrom:
            secretKeyRef:
              name: nfs-auth
              key: UID
        - name: PGID
          valueFrom:
            secretKeyRef:
              name: nfs-auth
              key: GID
        volumeMounts:
        - name: config
          mountPath: /config
        - name: videos
          mountPath: /movies
        - name: downloads
          mountPath: /downloads
        ports:
        - containerPort: 7878
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: radarr-config
      - name: videos
        persistentVolumeClaim:
          claimName: nfs-media
      - name: downloads
        persistentVolumeClaim:
          claimName: nfs-downloads
      - name: nfs-auth
        secret:
          secretName: nfs-auth