---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lidarr-postgres
  namespace: media
spec:
  encryptedData:
    password: AgCDE5nsOT/ykWOKIR25lnFMTqK5859N/lmZjT54WSFwIoPRzxRalV5QVsb0Wn7/rT/2tUTLMGlNShcdXA4+gBqWhiitJpHIC5LKMbWU4fV8qNSQTtRwB+8YeXH15a2nTIYofxwVrD5nVuUID6ernHOsqHVNB3W9AyZXBchg6tmf1npg9gjRWTH3/J0JdKcDDu1I+Tl3QHY/jshtbZEkLze4CBpzNyGW7JKGzx8B4Etb/Wsry7JZ1tZEEF33WDtPATkECrio6DnJ0V70tXSNpRCRG5tSK114FHQr6SdzqqiyQE7swm4CY5TH+YsuRpC7hz/Vd44YNfQWWFfgP1APGnIQUX+I3wlcV8o2kW19aBdLbg1i7HcPzYwyp1sm1DITWoyQ3V9aGB3FHDsN6ablACNWLIH9UqMQ7BwOb3qdqJq2ezBmATVQYSQrI/a3EaFTLEcJIQvmZRQYoikTpIIY2gSX12HXNT/ydl2GxuvblwyRQ5+jMdzvdqnYNAKy0R3YZAPx088vtF3VBvpk/H7WKytWe0TflxFDmKubFW/fYyXoQQhUojQKDTEpUba0AV06/CeVYIazD7LkS2exF4KvfQnf04ZEPHmwgeID6d3xdAd42YktMzQdUJsPMGioM+Bup4/KNulnyHSvPAuM4hAKMxEMSR6VP+BoTLT4hYh9LuFHY76reS7dteDiX7EFBJswp6W+Igqi/xz+czcxIYBLimO1L5gZk2o=
    username: AgCD+CLxk73sxzftK9CWKIspUWNj/bA2ULGuUxjoNDkePtJk73R7fe+fwPI6Ohmll3C3lQr46zDzC3FTJKTtxTQWROMY/ky+A4xyUWL9wsUaXs5TrWfF9/AfX10xkiI0C5SCj6Cvtv0DPnkStmL5vXfyHLeQ98tppraBnMCQAa7nlXZGbw3cjY2WX1KqZCkiBLdPVsJpLvU5jA/uieGjXN4Ylf064snKGg5g1DwH2by4arAqOy7wmn21NrwisrYZ7bFiiggb8xhUmDT4EvjoQ3Oub5xfChDuHwJBwMBaG+3HpmxQdWtfbSULRflakZAsK1QiPfwj2D/7yiTCe9WXs/SmQHXu2hIW8H2KZqbxp4oBManJLLBCzR+VA6yFXgmOY27s6NCOXjFypfODuOqVqPGS1Vc2FGwRENsr4ExmhZhcI7JYWzAsMc2c4PNZ+0AdxMsJOk0IpU5SKE7SVnUDm1EKGN5Db/4xY83+qCWv2yokq/Z9IEVsmDFziYanbwgDoxevZ22TK+Npty6cSFw0Rw6KjX/CEyNzWTbGErnYeF0WM9/vvf97ozigkw42qFN4rPnGFpTX9dpd36/X7JuirBox6h9mMWxhXrPzBz7ZTMp0yNhvKupPdpLq3U0PoobdcxQX5smI1xzFpqKdBBBXsYVGnX19qZW/ifWia0MGHuSRrJNSgz0DL+DOZC4mZflwGj6PkFb4/XU=
  template:
    metadata:
      name: lidarr-postgres
      namespace: media
    type: kubernetes.io/basic-auth