---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lidarr-postgres
  namespace: media
spec:
  encryptedData:
    password: AgB2geRzvH3kNCv0B+Z6rb8Xq7g92H3ksoAn3D+YnW5hQ3kG/9IhLrc81O9xIfrVqGCKC2hS38ipP9CauL2G3eGiYPT9fyu1CDCfqjkRhnD9NT3ErRI93UEhj5QAwtUsN6CpUz3hGMPrQYQ8V7hMcybLQD8hGfyrTRpRqVXEfzntiVMktCzp2ulLdnkdjdl2SNgn4GPBCROIvYImaO4Gb/DCKCgFIR9Jpfz+QmC8lWfmfAjRJqAb2uLhx0Q09wuRhn//A996uZQujoF2lum4vvnhg2GPj+PVbwr6oWB8SbXt3CpZwUCPvixygTSTY1Fg3wUvC91yxf5QrAqF5CUcqogncA0Z6j8mOsga2sE1+LZhLR34P24Hlec9U/Qy3j1KAf4Oes+toN1Twq0tdhMxBZ2Fd+BTMcHuCQB1dXEM2ohq7xScdmfqsGix3Lfq1EgOSc9EEGFYT+/G8i148maohW8t55uGRGb/p8n4JszZtALEq61knFnl16lkLewLaBJQ4n5AFw3PEjeYaEyirmHpL1JyzzaUbLTflWCKQrcxgb01q29Gy7ouc/sEHpsARmve9U7nK924M0OixYpm3jGtVMAEPudlmzv0cQo6/8wwr6MdRqGoBoLCbIUj4T2WDoX/uhf5pwUtjGPo5arOhYSRdep6A0MAjNTpKSPRFrPFMKtCTP3UrQkBJSxwIVIyil31+BvJeYvtcLD2DvA5eGh0kgFAQx6vP+I=
    username: AgB2c8BPHOYvDbzMpBvb7k7yFBau8paDjeoZ7bueu5qoFXy/UoVCBqUM6wpX8tz0C+wxFpXUUkmzhKiGDBZCsokjAf3DawCEzpN0ZrNKVg1rqZaDY5T9pXAnE82ba0SwRE4fZMB/KKOwUpq4uFSqF3GUYftdQd3gH/bax94MF6DieKmyNZb3SmQjYD563+jxSkY0xrN3w0L7S5shoKFhVH3qdtWZNlZUoAgj8G4eOmwuZbUd4eUSKWkXbnkTE0AG1cNe6V7x9jBqHsNINybS4sS6QdUJdj5NrudRoMLVf32/dR+RtA9Ttx4eZI3EJgMfZpXdskIL6zuddSI3yG5AQjqKWi+eF0hchIPnm/QngKTeN5lTljsDL/0fabfuU90Xbs9assKPceka8Adr19ePa18Z0aun+R4iT/LYQsuq525rmYzLqQS1Lbsw+lA/VqQPopzFXgpD9Bf5WCsMydgPMCPD3EYKUqXk8iDEON/keZsLTdlFyaKaz4MW6K9/sqkLcdLbHPLfNdx/JOL405kSWYE8l5t4dD/eQS5KrMKkooPPs5c7knCM82DE1xTJSH8oB/XTuXscnxQ5ndli9yrfPxk2iDnkmYDjVnz4iro0NmZuAEGFsAzvlkJzMUgTx0/OLhRLreb25vFx2yCMruZtMnx2peY6PZKnFjWeNZYBCa7dXYtmaIS8BWHAA7HqJokR0SzXYDH8r38=
  template:
    metadata:
      name: lidarr-postgres
      namespace: media
    type: kubernetes.io/basic-auth