apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallos-config
  namespace: tools
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi