apiVersion: v1
kind: ConfigMap
metadata:
  name: exclude-sync
  namespace: cilium-secrets
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous