---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mullvad-config-secret
  namespace: media
spec:
  encryptedData:
    wg0.conf: AgBkWKoYGwetKWx9vtc1tdrNW7WuToRrPlnZeae56Jlh8YX0sWYNNGkkStioOZq8PZot22QRE5fW9M3zHPVaBrSitSVQ0xz6TxraV698mQKdhITnziJDDO06HvGzEH1SBZtMoRE2AtNiGjeqjVGe2jyx5J6BU4VUktvWj7RbokZesTJTHE0RNKF5asxK4cOFfVaTjemk2BahWe6c8dqa75nsDM54d3rNtjo9xNzhK5ywEXcZPfm80Sk5ReZS9ejr16DKsjrZnHcwrpDI87vuS7oG/A8iRo1d/uGQuVu0TKPAzpKwTRNdV3NAvO/D14Yp+/tgfh7mQw9GCPzyfsBl7PIMO+EHkzdOIuX18QMB0QxIp7tLsxi5hQczPXh0FW2RaBAe6CpTIXI0/0Bi1BvJ3jYzHE9uBPgnbIFPiV601S57oJH6T5LzAtHKMcJM/+JnW19UwY+yiNwBItb9uLYxaLJfOQbozUc0K4hrLRWZGTvjyDJ+/XcUpj9p3UuI//Q5L2l98VFHH5hABpxFC1SASh7V4X6lRl5WYFk8B+/Nfh3MJ3ShvfEwnX58dmgtGKd4h73F8OxwaMZeAjLpfNtv2sNDnMHCtu+fWtIkHCtDbad6qQ4eXfuTfKGLK6Q0Zn93e9ToPlJyZ7BUFC520o94DwPfu4lx/8td6e7HlqitiN10S1ZmQCw3LtegQ0fLI9xcSnk8gqoShUdSQ04GvMl4AvaeRTn4aG8Q8qv7pIhQbp0fUjLZeB0GTkI1ZP29/ryav6F9cQRCCntZT8YCD3D7kB62uvtKjh8u9d3JumvRWg7y70UIYZZA3uHHo7OpFD4OQWyD8WHzqCZV3ivYT4z67xZR3e88lspxJFCMG9vAgQ1ouv18J9S05Avac22WkjroT6UbjGxzxGLvtkSdEYfIjjnbEgsvl9Z61v6omL06U+GtBpQsmoqPPCHCE1v4Ru2thCvd16lHmeCfMNQVYW72UgS2xm/N7XpC80FKX14FkkpEo/8AbcQNgIR3fe2fBkU6ZxvdyA3ilXO62my1GKfl
  template:
    metadata:
      name: mullvad-config-secret
      namespace: media
    type: Opaque