apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sonhs99/kube-bootstrap.git
    targetRevision: main
    path: "argocd/auth/authentik"
  destination:
    server: https://kubernetes.default.svc
    namespace: auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true