apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backrest-pvc
  namespace: backrest
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi