apiVersion: apps/v1
kind: Deployment
metadata:
  name: slskd
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slskd
  template:
    metadata:
      labels:
        app: slskd
    spec:
      initContainers:
        - name: render-config
          image: alpine:3.22
          command:
            - sh
            - -c
            - |
              apk add --no-cache gettext
              envsubst < /template/slskd.yml > /config/slskd.yml

          envFrom:
            - secretRef:
                name: slskd-auth-secret
          volumeMounts:
            - name: template
              mountPath: /template

            - name: data
              mountPath: /app
      containers:
        - name: slskd
          image: slskd/slskd:latest
          env:
            - name: SLSKD_REMOTE_CONFIGURATION
              value: "true"
            - name: SLSKD_SHARED_DIR
              value: "/mnt/music"
          volumeMounts:
            - name: data
              mountPath: /app
            - name: media
              mountPath: /mnt/music
              subPath: Music
            - name: downloads
              mountPath: /downloads
          ports:
            - containerPort: 5030
              name: slskd-http
            - containerPort: 5031
              name: slskd-https
            - containerPort: 50300
              name: slskd-listen

        - name: gluetun
          image: ghcr.io/qdm12/gluetun:v3.40.0
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "mullvad"
            - name: VPN_TYPE
              value: "wireguard"
            - name: FIREWALL_INPUT_PORTS
              value: "50413,50300,8080,5080,5030,5031"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "192.168.0.0/16,10.0.0.0/8"
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: DOT
              value: "off"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: tun
              mountPath: /dev/net/tun
            - name: mullvad-config-secret
              mountPath: "/gluetun/wireguard"
      volumes:
        - name: mullvad-config-secret
          secret:
            secretName: mullvad-config-secret
        - name: media
          persistentVolumeClaim:
            claimName: nfs-media
        - name: data
          persistentVolumeClaim:
            claimName: slskd-data
        - name: downloads
          persistentVolumeClaim:
            claimName: nfs-downloads
        - name: template
          configMap:
            name: slskd-config-template
        - name: tun
          hostPath:
            path: /dev/net/tun
        - name: nfs-auth
          secret:
            secretName: nfs-auth