apiVersion: v1
kind: Service
metadata:
  name: synology-dsm
  namespace: external
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 443
      targetPort: 5001
      appProtocol: https
---
apiVersion: v1
kind: Endpoints
metadata:
  name: synology-dsm
  namespace: external
subsets:
  - addresses:
      - ip: 192.168.88.31
    ports:
      - port: 8006