apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: arr-postgres
  namespace: media
spec:
  description: PostgreSQL cluster for the ARR stack
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17

  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      encoding: UTF8
      localeCType: C
      localeCollate: C

  storage:
    storageClass: longhorn-pg
    size: 10Gi

  walStorage:
    storageClass: longhorn-pg
    size: 5Gi

  postgresql:
    parameters:
      timezone: Asia/Seoul
      log_timezone: Asia/Seoul
      
  monitoring:
    enablePodMonitor: true