---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sonarr-postgres
  namespace: media
spec:
  encryptedData:
    password: AgB1K/aiE3nCW+8RT1K9xaEy+MRl5tsOXe5T+heJRBSjw8YNZlpeCRM2StHo7lV+flt4QDnWNUf66QEm1ssP8dCUYsaGwh1rOwjGOfZBVYq1bSnYvwsDX+Vk9SkBy7NFvHdL8Qr92O8zOYy66ql3omeiHx/4BQjdy8g3pvc+p/vc+O7Y+DbfqU2e5AriUKFL1lf1ocrV7O50722lHY4rEj/bGOTShLeVh8jYIvCywFbUKWsSxa01HYrFzEivnRgcGxPz8Oz2G4jVqSpyyFsV3zl5rbo50kIap4olft+qS7NywDejNVEjj/ISSdLmT46ps6m3/Wq4re4WSMqjQN5h6rciimdWBMBEPlI3irD+5oaerXp38Q7CSGt4yaajBSUkQKpX88SnpnU893dwPr4mhI/8AiCM2RmbyeAJvQrfZxXgqYABGv/vhsAIeyAcAifZXd/t50xuGzFIj3xkCz6e/zBFY9ELv6O1ZaaCjdY6Ri67npZ03pvQrTujiMHjzzwQRZ+bv4Jokkq4uVE1TJGlVfVw3ZE+elbwtp8h3MkzYa11iLqOCUmH+I+KAHwic/MO0e506mOKs1lf1qX6MexfJaI3qOdwLrCwVU7VOL/5c94FOdnQc4yQO5/tqoKZzv4ClDeqm3fuDh4Zd6Et8l647t69bz0qb1kwdfuuMRcfu+OtV2l+fZWNQGcOmEb43q74lJpgF6WRjyv4sZEQXLyMUlj8sVqK9w==
    username: AgBaKbtRFXQPvtLbLChp2aNY4UhZuQQqpB3biMKufON2VNGdlrcvtTugTohg0ViFw3Y88cLmYYD73FcTLd4eoSHtbxEXDt/NREzSSECH8mZJpUmtlk9Sc2uOxL2+yFG848d3BVXpDFvUfz3x6M08OpCdvTy9JsWnwn9w/DNAtO81dZRigdR8OW8J3NJ//iUdppSh0yIMCrOSURIqz5Ha0jRl2dOa3K7hXmVvzYUEZzEUsZbcGqvokjHn3LWdQqkt3uPUgIYCjejkjen/he3HmRaRrvYCwTWin4lY3hQxw44rUDgD/A5GXDli/qj5VxONg7Qqb2k6ooxyisVx17zd2cM0ife5WLKeft8iEgQTXGQ8rQNuDKrCk6OPhl5vmoyYhHAcDSjeDeHMUReAsNKBe2d1wNRo6iW+AzTpohTYNOovbPodOSu+053n97NS63B6DZKFJNv4S5n5Tdxu0BMrCTZkjgCTYWIVzJrj1FT01dgD4WvmS0yaPtr2GEJFf0mY2+h3aOidyR2aA/53qVTHqaSlvHqJnAIkudPWQt/cz2s2h2yEKnOvA/jQL7iiQ13HXK4uHMyPSrENuWyu5w1XYPqwmdP6oe6YxOF1pAg02YkWniaqg7/Z8o0xLaAoheM6rnvuI5Xxe07vDOP4UfXzJ4tVZf0zYNyZeE/HVx5SvM2SgT6EjQrBc1m6Ynd9GACCjRgHTXuwm78=
  template:
    metadata:
      name: sonarr-postgres
      namespace: media
    type: kubernetes.io/basic-auth
