apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 10.5.15
    chart: grafana
    helm:
      values: |
        datasources:
          - name: Prometheus
            type: prometheus
            access: proxy
            url: http://prometheus-server.monitoring.svc:80
            isDefault: true
            editable: true
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true