alertmanager:
  service:
    type: LoadBalancer
    port: 80
    targetPort: 82
    loadBalancerIP: "192.168.88.156"
    nodePort: null

grafana:
  defaultDashboardsTimezone: Asia/Seoul
  adminPassword: prom-operator
  service:
    type: LoadBalancer
    port: 80
    loadBalancerIP: "192.168.88.156"
    nodePort: null

prometheus:
  service:
    type: LoadBalancer
    port: 80
    targetPort: 81
    loadBalancerIP: "192.168.88.156"
    nodePort: null
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: 5d
    retentionSize: "10GiB"
    scrapeInterval: "15s"
    evaluationInterval: "15s"