apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lazydogs-work-cert
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  isCA: false
  secretName: lazydogs-work-key-pair
  commonName: lazydogs.work
  dnsNames:
    - lazydogs.work
    - "*.lazydogs.work"
    - "*.internal.lazydogs.work"
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 4096
  issuerRef:
    name: letsencrypt-dns01-prod-issuer
    kind: ClusterIssuer