---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: kube-system
spec:
  encryptedData:
    api-token: AgATFNKJP3BGk/ncWOkgdh/9wf4XkqmfhCtfKZNJmagAC31bSAhucH4XrMVXUXP1twQUiZoTJSmnvwY6xmkEK0B1wsW9c0LknaW4tdCnpQnanDEz5i2LKbXWVRuZV1PZ/slRIQ6IS9lOvAEO/rzOJ4fpApi8hLFXvTJ/upnI4meGE1oOM3lHY2dBnGZWEJ6OM6UmnKksQv5IOY+pqirP9PN/JN+3p4ayAvsOHLG63DoAfIvZ2+qOc8WLVqJ1wgPiUIHrd6D/+qR9ymCbFrBHmXMrAi4IN3+pnQsUXYfXU0oceXp4tJQVEULTqlRuBvCovXZchyiPmgOmSOIcWWfoHaPpUoyGm2mtb4uu0zg8q3HA43vStzai6eQK4eELv7OnVmoG8S979GpL3YCG/PKQTOMIQRw6y4W22ClBBk1flZb+70tR6U3HjKQvgTWpQa0wtkUPZaRWglDreh4LtlcmyoN1PxtRh/vTLF3nMCWkgp2mtvgGJdJxe0ioWQODJ47RjZY3YBkj1bEqhkLtXiTyaYq3mmiQo7fw/aloPwW/C15Ls+Gp3hvA9HKRKbaL/PdHPM5wEy1hJHZtO7IgHWFaMVo3wATZJl0rT1CLFO6ODzFCWDMVxGq48RcBv80yikPRse1ZTcwjnrrzKZNiCAbSwGXGa4X26vkMpeNhP6n9VNlyviCobW659mNIZOJ4xoxC+KyYkxN4bspXvvxz351H3soKFFUb7vI+TiO+KGk1uBAOYR6B3cxgOvP8
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: kube-system
    type: Opaque
