---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgB66MOm/tT1Dh6NYE0cb4lbLbcp7zGCOoBxoeBGajW6adtV5N0YcQaAx3Mt0KfZ0lpn+pv6/nmlj5CpQv3bzvI6fy+ONCHzipKOhQlqWvl8Qs4+fZ0gPxOMnqPuLJNMcYn+VTpXIweh49wS9X03RJJGGVd1Z3ClMP587LyofH0bP8ig+7bJEHnIjinYZFqhuziP4iaLZp7tGjbLXmBvWrXNUWsFO6oAMrXBT8Z1WF0j+9DWFTrcpIsO32Famn7czMESUroRz+TaBiHcDFo8Bt4wodaReMFvMOrSLxFT6TkVxjBvPSrCXjH4j8kqX7kv07WBs078x6WWQtRaKaQIiQ6QXymKT+bGrOBrJzHi7xpr1wIuEYHMDJ4l+2b2cFx8O+gsHhGioT1cxnVIS1t+LpvueULp7i+mLXwvCfyp4eKei7l3Sk/YBg7lisWjHEp15zSu7OBB85bJIoVsPFqGOLUhW+3MowhpOGTkcmYoOPhu48i/pn5ramKW0yhaA9hiYsd4TotFVtzcpWih1djXsFXu+rs3Bmo2SDjJgMC+3c7FuANDWiI3Hf0yXgIjapJ2wx2TaoqSqMkTTexSq6CWKP6gWHv08eOhymi8idSjqDlBN3mbtS/BL4uBXiD838jvuyTP4hwiGDHXCPooggi84ba+up7VpDS1gp5zNnjRgHQCZZO314bXJUS5HhCSr/45aUyWOU/oJR2AuSpFYrmBC1PmjUd7K4vc+JmL/rWuDB47XOYKUlKoCrZT
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
