apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: kube-system
spec:
  encryptedData:
    api-token: AgBRT6jp1yelIS1yat0uQE8+ARLDPqJBJe3YNBFUQpsg+sQvl6o8afIJNQvidD1KI5IiUMPczGz1CMogmrfDmd6fLjRY/wDYmdt9fiiHZdKctxF4VXG7v5vsWzyETUA+MLNGTcRy1v+x/wekcUUwMr+gmQpD+/S7ARaavFgJgmrs2Gwqjy6jjHiAW1jw7hBqm/MBiUU+aFThUhvoemZclcj192wfOQVbyVuRuBbtBGeNcG5dUnj4LojKH4r/rpHtxECGiPljxjfh0S2U0VDfo0O0n26b/yTFHIx/KQeSAPnhX7jer8p0oiAovffPy5SafX0LwZt4oVs8wUBU85aWjZ8yl2kNYcDpfu/iAvPwaus1KsD1DJ4oVU+hls7UWL6fB42e+Yy2cnXVngtYpL7mSX4Z1IjScE7CBkHdawgc4Uvb/Z/NBKnqrzjmnlAswva2B/LLNaI77BaghOqYlHIwRtqU1DGpqT9ju0qJ7Z3min9MxKTuhSff2BOxPkOA9luJ9c085JGCouV6R6dpc2o8nBABpsK60Wp5cCwkUtb+lU0Y4MBS+F5re+5ZGGcM8JQ6jz3P4jztku90pB4hYxUMXKS8TdIzGyKrV8UO5W4tUtSmV9Gh7lFpOQ/Pw58gqZc6H8WCHf0Hvme5ZhidRbh9GXv0Uw/lmFJgu1YwDaYsN1udln4UdAoZb1vsSqmBK/AEMiZUFZghTMwgxRnY6pFo/GG1l9NocYCWP9p+q04a0pTGSMnjfqI4D5J3
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: kube-system
    type: Opaque
