apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent
          resources:
            limits:
              memory: "2Gi"
            requests:
              memory: "512Mi"
          env:
          - name: PUID
            valueFrom:
              secretKeyRef:
                name: nfs-auth
                key: UID
          - name: PGID
            valueFrom:
              secretKeyRef:
                name: nfs-auth
                key: GID
          volumeMounts:
            - name: data
              mountPath: /config
            - name: downloads
              mountPath: /downloads
          ports:
            - containerPort: 8080
              name: qbitt-http

        - name: gluetun
          image: ghcr.io/qdm12/gluetun:v3.40.0
          env:
            - name: VPN_SERVICE_PROVIDER
              value: "mullvad"
            - name: VPN_TYPE
              value: "wireguard"
            - name: FIREWALL_INPUT_PORTS
              value: "50413,50300,8080,5080,5030,5031"
            - name: FIREWALL_OUTBOUND_SUBNETS
              value: "192.168.0.0/16,10.0.0.0/8"
            - name: DNS_KEEP_NAMESERVER
              value: "on"
            - name: DOT
              value: "off"
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: tun
              mountPath: /dev/net/tun
            - name: mullvad-config-secret
              mountPath: "/gluetun/wireguard"
      volumes:
        - name: mullvad-config-secret
          secret:
            secretName: mullvad-config-secret
        - name: media
          persistentVolumeClaim:
            claimName: nfs-media
        - name: data
          persistentVolumeClaim:
            claimName: qbittorrent-data
        - name: downloads
          persistentVolumeClaim:
            claimName: nfs-downloads
        - name: tun
          hostPath:
            path: /dev/net/tun
        - name: nfs-auth
          secret:
            secretName: nfs-auth